spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
management:
  endpoints:
    web:
      exposure.include: metrics,prometheus
---
spring:
  config:
    activate:
      on-profile: prod
