global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path: defaults to '/metrics' and scheme defaults to 'http'.
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # this should be the target host IP which is outside of the docker:
      # 172.17.0.1   or   "export DOCKER_GATEWAY_HOST=$(hostname -I | awk '{print $1}')"
      - targets: [ '172.17.0.1:8080' ]
